title: "Krnivoro | Experiencias Gastronómicas y Networking de Alto Nivel"
email: info@krnivoro.com
phone: +52 661 172 4066
address: Rancho Oasis, 22760 Ensenada B.C México
description: >-
  Conectamos líderes visionarios a través de sabores memorables, vínculos estratégicos y experiencias exclusivas que trascienden fronteras.
image: "/assets/img/krnivoro/favicon/apple-touch-icon.png"
twitter_username: krnivoro
facebook_page: krnivoro
instagram_username: krnivoro
lang: es_MX
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://krnivoro.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
google_analytics: G-EJ1YZFT2KJ


# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

twitter:
  username: CentroRosarito
  card: summary


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
# collections:
#   servicios:
#     output: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - service-details.html
  - portfolio-details.html
  - starter-page.html
  - index_.html
  - inde.txt
  - servicios.txt
  - servicios.txt

defaults:
  -
    scope:
      path: ""
    values:
      lang: "es-mx"
      lazy: true
      image: 
        path: /assets/img/logo-krnivoro-og.jpg
        height: 200
        width: 200
      author: Rosarito Centro